CREATE TABLE TLG_MSG (
    ID  VARCHAR2(40 BYTE)   DEFAULT SYS_GUID() NOT NULL,
    DT  TIMESTAMP(6)        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    KEY VARCHAR2(32 BYTE)   NOT NULL,
    MSG VARCHAR2(2000 BYTE) NOT NULL,
    PRIMARY KEY (ID) USING INDEX
);

CREATE TABLE TLG_GROUP_KEYS(
    KEY VARCHAR2(100) NOT NULL,
    CHAT_ID NUMBER NOT NULL,
    DT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL
);